# name: bayeseor
name: bayeseor2
channels:
  - conda-forge
dependencies:
  - astropy
  - astropy-healpix
  - cuda
  - gcc_linux-64
  - h5py
  - jsonargparse
  - magma
  - matplotlib
  - mpi4py>=3.0.0
  - numpy>=1.26,<2
  - pip
  - pycuda
  - pymultinest
  - pytest
  - python==3.12
  - pyuvdata
  - rich
  - ruff
  - scipy
  - setuptools
  - setuptools_scm
  - sphinx
  - threadpoolctl
