name: bayeseor
channels:
  - conda-forge
dependencies:
  - astropy
  - astropy-healpix
  - gcc_linux-64
  - h5py
  - jsonargparse
#   - mpi4py>=3.0.0
  - numpy
  - pip
#   - pycuda
  - pymultinest
  - python
  - pyuvdata
  - rich
  - scipy
  - sphinx
