name: bayeseor
channels:
  - conda-forge
dependencies:
  - astropy
  - astropy-healpix
  - cuda
  - gcc_linux-64
  - h5py
  - jsonargparse
  - magma
  - matplotlib
  - mpi4py>=3.0.0
  - numpy
  - pip
  - pycuda
  - pymultinest
  - pytest
  - python
  - pyuvdata
  - rich
  - scipy
  - setuptools
  - setuptools_scm
  - sphinx
  - threadpoolctl
