# Compute params
useGPU: True
# Frequency params
nf: 38
nu_min_MHz: 158.304048743
channel_width_MHz: 0.237618986858
# EoR model params
nu: 15
fov_ra_eor: 12.9080728652
nside: 128
# Noise params
sigma: 0.00615864342588761
# Instrument model params
include_instrumental_effects: True
nt: 34
integration_time_seconds: 11.0
inst_model: ./test_data/
central_jd: 2458098.3065661727
beam_type: gaussian
fwhm_deg: 9.306821090681533
# Data params
data_path: ./test_data/visibilities.npy
# Prior params
priors: [[-2.0, 2.0], [-1.2, 2.8], [-0.7, 3.3], [0.7, 2.7], [1.1, 3.1],
         [1.5, 3.5], [2.0, 4.0], [2.4, 4.4], [2.7, 4.7]]
